enabled: true
root_page: 					                                # optional: set root page of documentation
top_level_version: false                            # Use versions for top level navigation
google_analytics_code:                              # Enter your `UA-XXXXXXXX-X` code here
home_url:                                           # http://getgrav.org
logo_url: 'https://ginkgostreet.com/sites/default/files/ginkgo-street-labs.png'
github:
    position: top                                   # top | bottom | off
    icon:                                           # FontAwesome icon
    tree: 'https://github.com/ginkgostreet/ginkgo-docs-grav/tree/master/'
default_taxonomy_category: docs
style: default

streams:
 schemes:
   theme:
     type: ReadOnlyStream
     prefixes:
       '':
       - user/themes/ginkgo-rtfm
       - user/themes/learn2
hide_site_title: true
